name: firebase_flutter_proyectlockers
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.4.1


dependencies:
  wifi_info_flutter: ^2.0.2
  awesome_dialog: ^3.2.1
  connection_status_bar: ^1.1.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  awesome_snackbar_content: ^0.1.4
  http: ^0.13.4
  flutter:
    sdk: flutter  
  flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.7.0
  connectivity_plus: ^1.4.0
  go_router: ^14.3.0
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^27.1.56
  gestures: ^1.0.0
  table_calendar: ^3.1.2
  cloud_firestore: ^5.4.4
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/IconoLocker.jpg"


flutter: 
  uses-material-design: true
  assets:
    - assets/images/Safe Safe.jpg
    - assets/images/cajatriste.png
    - assets/images/cajafeliz.png
    - assets/images/cajaterminos.png