name: firebase_flutter_proyectlockers
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  awesome_dialog: ^3.2.1
  firebase_core: ^3.3.0
  awesome_snackbar_content: ^0.1.3
  flutter:
    sdk: flutter  
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.2
  intl: ^0.19.0
  syncfusion_flutter_datepicker: ^26.2.7
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/IconoLocker.jpg"


flutter: 
  uses-material-design: true
  assets:
    - assets/images/Safe Safe.jpg
    - assets/images/cajatriste.png
    - assets/images/cajafeliz.png